def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']

setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  'Notifications',
  'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReturnBuddies' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  use_modular_headers!

# --- Fix for React Native 0.82.x missing fast_float ---
pod 'fast_float', :podspec => '../node_modules/react-native/third-party-podspecs/fast_float.podspec'
pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
# -------------------------------------------------------

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..")


pod 'NitroMmkv', :path => '../node_modules/react-native-mmkv'
# -------------------------------------------------------
pod "FirebaseCoreInternal", :modular_headers => true
pod "GoogleUtilities", :modular_headers => true
pod "FirebaseAuthInterop", :modular_headers => true
pod "FirebaseAppCheckInterop", :modular_headers => true
pod "FirebaseCore", :modular_headers => true
pod "FirebaseCoreExtension", :modular_headers => true
pod "RecaptchaInterop", :modular_headers => true
pod 'Firebase'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    target 'OneSignalNotificationServiceExtension' do
      pod 'OneSignalXCFramework', '>= 5.2.1', '< 6.0'
    end
  end
end